apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-hello-world
  namespace: default
spec:
  selector:
    matchLabels:
      app: web
      name: pf-hello-world
  template:
    metadata:
      labels:
        app: web
        name: pf-hello-world
    spec:
      containers:
        - name: pf-hello-world
          image: sonnguyenep/pf-hello-world:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pf-hello-world
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: pf-hello-world
  sessionAffinity: None
  type: ClusterIP